# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_sub_window_2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1158, 779)
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(850, 10, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setGeometry(QtCore.QRect(240, 60, 900, 700))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image.setFont(font)
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.pushButton_open_file = QtWidgets.QPushButton(Form)
        self.pushButton_open_file.setGeometry(QtCore.QRect(20, 20, 191, 28))
        self.pushButton_open_file.setCheckable(False)
        self.pushButton_open_file.setDefault(True)
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 211, 191))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 151, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_zoom_factor_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_zoom_factor_1.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_zoom_factor_1.setFont(font)
        self.label_zoom_factor_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zoom_factor_1.setObjectName("label_zoom_factor_1")
        self.horizontalLayout.addWidget(self.label_zoom_factor_1)
        self.label_zoom_factor_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_zoom_factor_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.label_zoom_factor_2.setFont(font)
        self.label_zoom_factor_2.setText("")
        self.label_zoom_factor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zoom_factor_2.setObjectName("label_zoom_factor_2")
        self.horizontalLayout.addWidget(self.label_zoom_factor_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_zoom_in = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_zoom_in.setObjectName("pushButton_zoom_in")
        self.verticalLayout.addWidget(self.pushButton_zoom_in)
        self.pushButton_zoom_out = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_zoom_out.setObjectName("pushButton_zoom_out")
        self.verticalLayout.addWidget(self.pushButton_zoom_out)
        self.pushButton_zoom_reset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_zoom_reset.setObjectName("pushButton_zoom_reset")
        self.verticalLayout.addWidget(self.pushButton_zoom_reset)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 211, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 191, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_srcImage_size = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_srcImage_size.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_srcImage_size.setFont(font)
        self.label_srcImage_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_srcImage_size.setObjectName("label_srcImage_size")
        self.verticalLayout_2.addWidget(self.label_srcImage_size)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_5.addWidget(self.label_1)
        self.spinBox_anchor_x = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_anchor_x.setMaximum(99)
        self.spinBox_anchor_x.setObjectName("spinBox_anchor_x")
        self.horizontalLayout_5.addWidget(self.spinBox_anchor_x)
        self.spinBox_anchor_y = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_anchor_y.setMaximum(99)
        self.spinBox_anchor_y.setObjectName("spinBox_anchor_y")
        self.horizontalLayout_5.addWidget(self.spinBox_anchor_y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBox_X_offset = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_X_offset.setMaximum(99)
        self.spinBox_X_offset.setObjectName("spinBox_X_offset")
        self.horizontalLayout_4.addWidget(self.spinBox_X_offset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_left_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_left_2.setFont(font)
        self.label_left_2.setObjectName("label_left_2")
        self.horizontalLayout_2.addWidget(self.label_left_2)
        self.spinBox_Y_offset = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_Y_offset.setObjectName("spinBox_Y_offset")
        self.horizontalLayout_2.addWidget(self.spinBox_Y_offset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton_screenshot = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_screenshot.setGeometry(QtCore.QRect(20, 200, 171, 28))
        self.pushButton_screenshot.setObjectName("pushButton_screenshot")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图像的缩放与裁切"))
        self.label_title.setText(_translate("Form", "图像缩放与裁切"))
        self.label_image.setText(_translate("Form", "图片将显示在这里"))
        self.pushButton_open_file.setText(_translate("Form", "打开图片"))
        self.groupBox.setTitle(_translate("Form", "缩放控制"))
        self.label_zoom_factor_1.setText(_translate("Form", "缩放系数："))
        self.pushButton_zoom_in.setText(_translate("Form", "放大"))
        self.pushButton_zoom_out.setText(_translate("Form", "缩小"))
        self.pushButton_zoom_reset.setText(_translate("Form", "默认大小"))
        self.groupBox_2.setTitle(_translate("Form", "裁切控制"))
        self.label_srcImage_size.setText(_translate("Form", "原图X轴*Y轴："))
        self.label_1.setText(_translate("Form", "锚点坐标"))
        self.label_2.setText(_translate("Form", "X轴偏移"))
        self.label_left_2.setText(_translate("Form", "Y轴偏移"))
        self.pushButton_screenshot.setText(_translate("Form", "图片裁切"))

