# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_sub_window_3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1334, 770)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(650, 20, 361, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_median_blur_filter = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_median_blur_filter.setGeometry(QtCore.QRect(10, 100, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        self.groupBox_median_blur_filter.setFont(font)
        self.groupBox_median_blur_filter.setObjectName("groupBox_median_blur_filter")
        self.label_title_3 = QtWidgets.QLabel(self.groupBox_median_blur_filter)
        self.label_title_3.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_title_3.setObjectName("label_title_3")
        self.spinBox_median_ksize = QtWidgets.QSpinBox(self.groupBox_median_blur_filter)
        self.spinBox_median_ksize.setGeometry(QtCore.QRect(100, 20, 46, 22))
        self.spinBox_median_ksize.setMinimum(3)
        self.spinBox_median_ksize.setSingleStep(2)
        self.spinBox_median_ksize.setProperty("value", 3)
        self.spinBox_median_ksize.setObjectName("spinBox_median_ksize")
        self.pushButton_median_blur_filter = QtWidgets.QPushButton(self.groupBox_median_blur_filter)
        self.pushButton_median_blur_filter.setGeometry(QtCore.QRect(30, 50, 111, 28))
        self.pushButton_median_blur_filter.setObjectName("pushButton_median_blur_filter")
        self.groupBox_gauss_blur_filter = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_gauss_blur_filter.setGeometry(QtCore.QRect(190, 10, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        self.groupBox_gauss_blur_filter.setFont(font)
        self.groupBox_gauss_blur_filter.setObjectName("groupBox_gauss_blur_filter")
        self.label_title_7 = QtWidgets.QLabel(self.groupBox_gauss_blur_filter)
        self.label_title_7.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_title_7.setObjectName("label_title_7")
        self.spinBox_gauss_blur_ksize = QtWidgets.QSpinBox(self.groupBox_gauss_blur_filter)
        self.spinBox_gauss_blur_ksize.setGeometry(QtCore.QRect(100, 20, 46, 22))
        self.spinBox_gauss_blur_ksize.setMinimum(3)
        self.spinBox_gauss_blur_ksize.setSingleStep(2)
        self.spinBox_gauss_blur_ksize.setProperty("value", 3)
        self.spinBox_gauss_blur_ksize.setObjectName("spinBox_gauss_blur_ksize")
        self.pushButton_gauss_blur_filter = QtWidgets.QPushButton(self.groupBox_gauss_blur_filter)
        self.pushButton_gauss_blur_filter.setGeometry(QtCore.QRect(30, 50, 111, 28))
        self.pushButton_gauss_blur_filter.setObjectName("pushButton_gauss_blur_filter")
        self.groupBox_mean_blur_filter = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_mean_blur_filter.setGeometry(QtCore.QRect(10, 10, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        self.groupBox_mean_blur_filter.setFont(font)
        self.groupBox_mean_blur_filter.setObjectName("groupBox_mean_blur_filter")
        self.label_title_9 = QtWidgets.QLabel(self.groupBox_mean_blur_filter)
        self.label_title_9.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_title_9.setObjectName("label_title_9")
        self.spinBox_mean_ksize = QtWidgets.QSpinBox(self.groupBox_mean_blur_filter)
        self.spinBox_mean_ksize.setGeometry(QtCore.QRect(100, 20, 46, 22))
        self.spinBox_mean_ksize.setMinimum(3)
        self.spinBox_mean_ksize.setSingleStep(2)
        self.spinBox_mean_ksize.setProperty("value", 3)
        self.spinBox_mean_ksize.setObjectName("spinBox_mean_ksize")
        self.pushButton_mean_blur_filter = QtWidgets.QPushButton(self.groupBox_mean_blur_filter)
        self.pushButton_mean_blur_filter.setGeometry(QtCore.QRect(30, 50, 111, 28))
        self.pushButton_mean_blur_filter.setObjectName("pushButton_mean_blur_filter")
        self.groupBox_double_blur_filter = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_double_blur_filter.setGeometry(QtCore.QRect(190, 100, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        self.groupBox_double_blur_filter.setFont(font)
        self.groupBox_double_blur_filter.setObjectName("groupBox_double_blur_filter")
        self.pushButton_double_blur_filter = QtWidgets.QPushButton(self.groupBox_double_blur_filter)
        self.pushButton_double_blur_filter.setGeometry(QtCore.QRect(30, 30, 111, 28))
        self.pushButton_double_blur_filter.setObjectName("pushButton_double_blur_filter")
        self.pushButton_open_file = QtWidgets.QPushButton(Form)
        self.pushButton_open_file.setGeometry(QtCore.QRect(30, 30, 101, 31))
        self.pushButton_open_file.setCheckable(False)
        self.pushButton_open_file.setDefault(True)
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 20, 461, 201))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_salt_noise = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_salt_noise.setGeometry(QtCore.QRect(10, 10, 141, 181))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(7)
        self.groupBox_salt_noise.setFont(font)
        self.groupBox_salt_noise.setObjectName("groupBox_salt_noise")
        self.label = QtWidgets.QLabel(self.groupBox_salt_noise)
        self.label.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.label.setObjectName("label")
        self.doubleSpinBox_salt_proportion = QtWidgets.QDoubleSpinBox(self.groupBox_salt_noise)
        self.doubleSpinBox_salt_proportion.setGeometry(QtCore.QRect(50, 30, 61, 22))
        self.doubleSpinBox_salt_proportion.setMaximum(0.9)
        self.doubleSpinBox_salt_proportion.setSingleStep(0.01)
        self.doubleSpinBox_salt_proportion.setProperty("value", 0.05)
        self.doubleSpinBox_salt_proportion.setObjectName("doubleSpinBox_salt_proportion")
        self.pushButton_salt_pepper_noise = QtWidgets.QPushButton(self.groupBox_salt_noise)
        self.pushButton_salt_pepper_noise.setGeometry(QtCore.QRect(20, 130, 101, 28))
        self.pushButton_salt_pepper_noise.setObjectName("pushButton_salt_pepper_noise")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox_salt_noise)
        self.radioButton_1.setGeometry(QtCore.QRect(20, 60, 101, 19))
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_salt_noise)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 80, 101, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_salt_noise)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 100, 101, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_speckle_noise = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_speckle_noise.setGeometry(QtCore.QRect(310, 10, 141, 181))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(7)
        self.groupBox_speckle_noise.setFont(font)
        self.groupBox_speckle_noise.setObjectName("groupBox_speckle_noise")
        self.pushButton_speckle_noise = QtWidgets.QPushButton(self.groupBox_speckle_noise)
        self.pushButton_speckle_noise.setGeometry(QtCore.QRect(20, 130, 101, 28))
        self.pushButton_speckle_noise.setObjectName("pushButton_speckle_noise")
        self.label_title_11 = QtWidgets.QLabel(self.groupBox_speckle_noise)
        self.label_title_11.setGeometry(QtCore.QRect(20, 30, 41, 21))
        self.label_title_11.setObjectName("label_title_11")
        self.label_title_12 = QtWidgets.QLabel(self.groupBox_speckle_noise)
        self.label_title_12.setGeometry(QtCore.QRect(20, 60, 41, 21))
        self.label_title_12.setObjectName("label_title_12")
        self.doubleSpinBox_speckle_var = QtWidgets.QDoubleSpinBox(self.groupBox_speckle_noise)
        self.doubleSpinBox_speckle_var.setGeometry(QtCore.QRect(60, 60, 61, 22))
        self.doubleSpinBox_speckle_var.setMaximum(1.0)
        self.doubleSpinBox_speckle_var.setSingleStep(0.01)
        self.doubleSpinBox_speckle_var.setProperty("value", 0.05)
        self.doubleSpinBox_speckle_var.setObjectName("doubleSpinBox_speckle_var")
        self.doubleSpinBox_speckle_mean = QtWidgets.QDoubleSpinBox(self.groupBox_speckle_noise)
        self.doubleSpinBox_speckle_mean.setGeometry(QtCore.QRect(60, 30, 61, 22))
        self.doubleSpinBox_speckle_mean.setMinimum(-1.0)
        self.doubleSpinBox_speckle_mean.setMaximum(1.0)
        self.doubleSpinBox_speckle_mean.setSingleStep(0.01)
        self.doubleSpinBox_speckle_mean.setProperty("value", 0.0)
        self.doubleSpinBox_speckle_mean.setObjectName("doubleSpinBox_speckle_mean")
        self.groupBox_gauss_noise = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_gauss_noise.setGeometry(QtCore.QRect(160, 10, 141, 181))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(7)
        self.groupBox_gauss_noise.setFont(font)
        self.groupBox_gauss_noise.setObjectName("groupBox_gauss_noise")
        self.pushButton_gasuss_noise = QtWidgets.QPushButton(self.groupBox_gauss_noise)
        self.pushButton_gasuss_noise.setGeometry(QtCore.QRect(20, 130, 101, 28))
        self.pushButton_gasuss_noise.setObjectName("pushButton_gasuss_noise")
        self.doubleSpinBox_gauss_mean = QtWidgets.QDoubleSpinBox(self.groupBox_gauss_noise)
        self.doubleSpinBox_gauss_mean.setGeometry(QtCore.QRect(60, 30, 61, 22))
        self.doubleSpinBox_gauss_mean.setMinimum(-1.0)
        self.doubleSpinBox_gauss_mean.setMaximum(1.0)
        self.doubleSpinBox_gauss_mean.setSingleStep(0.01)
        self.doubleSpinBox_gauss_mean.setProperty("value", 0.0)
        self.doubleSpinBox_gauss_mean.setObjectName("doubleSpinBox_gauss_mean")
        self.label_title_8 = QtWidgets.QLabel(self.groupBox_gauss_noise)
        self.label_title_8.setGeometry(QtCore.QRect(20, 30, 41, 21))
        self.label_title_8.setObjectName("label_title_8")
        self.doubleSpinBox_gauss_var = QtWidgets.QDoubleSpinBox(self.groupBox_gauss_noise)
        self.doubleSpinBox_gauss_var.setGeometry(QtCore.QRect(60, 60, 61, 22))
        self.doubleSpinBox_gauss_var.setMaximum(1.0)
        self.doubleSpinBox_gauss_var.setSingleStep(0.01)
        self.doubleSpinBox_gauss_var.setProperty("value", 0.05)
        self.doubleSpinBox_gauss_var.setObjectName("doubleSpinBox_gauss_var")
        self.label_title_10 = QtWidgets.QLabel(self.groupBox_gauss_noise)
        self.label_title_10.setGeometry(QtCore.QRect(20, 60, 41, 21))
        self.label_title_10.setObjectName("label_title_10")
        self.comboBox_noise_type = QtWidgets.QComboBox(Form)
        self.comboBox_noise_type.setGeometry(QtCore.QRect(30, 110, 100, 20))
        self.comboBox_noise_type.setMaxVisibleItems(10)
        self.comboBox_noise_type.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_noise_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_noise_type.setFrame(True)
        self.comboBox_noise_type.setModelColumn(0)
        self.comboBox_noise_type.setObjectName("comboBox_noise_type")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 100, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 100, 31))
        self.label_3.setObjectName("label_3")
        self.comboBox_filter_type = QtWidgets.QComboBox(Form)
        self.comboBox_filter_type.setGeometry(QtCore.QRect(30, 180, 100, 20))
        self.comboBox_filter_type.setMaxVisibleItems(10)
        self.comboBox_filter_type.setFrame(True)
        self.comboBox_filter_type.setModelColumn(0)
        self.comboBox_filter_type.setObjectName("comboBox_filter_type")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(1030, 30, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_image_3 = QtWidgets.QLabel(Form)
        self.label_image_3.setGeometry(QtCore.QRect(880, 280, 420, 400))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_3.setFont(font)
        self.label_image_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_3.setObjectName("label_image_3")
        self.label_image_2 = QtWidgets.QLabel(Form)
        self.label_image_2.setGeometry(QtCore.QRect(450, 280, 420, 400))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_2.setFont(font)
        self.label_image_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_2.setObjectName("label_image_2")
        self.label_image_1 = QtWidgets.QLabel(Form)
        self.label_image_1.setGeometry(QtCore.QRect(20, 280, 420, 400))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_1.setFont(font)
        self.label_image_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_1.setObjectName("label_image_1")

        self.retranslateUi(Form)
        self.comboBox_noise_type.setCurrentIndex(-1)
        self.comboBox_filter_type.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图像的加噪和平滑"))
        self.groupBox_median_blur_filter.setTitle(_translate("Form", "中值滤波"))
        self.label_title_3.setText(_translate("Form", "核大小："))
        self.pushButton_median_blur_filter.setText(_translate("Form", "开始处理"))
        self.groupBox_gauss_blur_filter.setTitle(_translate("Form", "高斯滤波"))
        self.label_title_7.setText(_translate("Form", "核大小："))
        self.pushButton_gauss_blur_filter.setText(_translate("Form", "开始处理"))
        self.groupBox_mean_blur_filter.setTitle(_translate("Form", "均值滤波"))
        self.label_title_9.setText(_translate("Form", "核大小："))
        self.pushButton_mean_blur_filter.setText(_translate("Form", "开始处理"))
        self.groupBox_double_blur_filter.setTitle(_translate("Form", "双边滤波"))
        self.pushButton_double_blur_filter.setText(_translate("Form", "开始处理"))
        self.pushButton_open_file.setText(_translate("Form", "打开图片"))
        self.groupBox_salt_noise.setTitle(_translate("Form", "椒盐噪声"))
        self.label.setText(_translate("Form", "比例："))
        self.pushButton_salt_pepper_noise.setText(_translate("Form", "确定"))
        self.radioButton_1.setText(_translate("Form", "椒盐（随机）"))
        self.radioButton_2.setText(_translate("Form", "盐（白点）"))
        self.radioButton_3.setText(_translate("Form", "椒（黑点）"))
        self.groupBox_speckle_noise.setTitle(_translate("Form", "乘积性噪声"))
        self.pushButton_speckle_noise.setText(_translate("Form", "确定"))
        self.label_title_11.setText(_translate("Form", "均值："))
        self.label_title_12.setText(_translate("Form", "方差："))
        self.groupBox_gauss_noise.setTitle(_translate("Form", "高斯噪声"))
        self.pushButton_gasuss_noise.setText(_translate("Form", "确定"))
        self.label_title_8.setText(_translate("Form", "均值："))
        self.label_title_10.setText(_translate("Form", "方差："))
        self.label_2.setText(_translate("Form", "添加噪声类型："))
        self.label_3.setText(_translate("Form", "平滑滤波类型："))
        self.label_title.setText(_translate("Form", "图像加噪和平滑"))
        self.label_image_3.setText(_translate("Form", "平滑滤波"))
        self.label_image_2.setText(_translate("Form", "加噪"))
        self.label_image_1.setText(_translate("Form", "原图"))

