# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_sub_window_5.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1269, 797)
        self.label_image_2 = QtWidgets.QLabel(Form)
        self.label_image_2.setGeometry(QtCore.QRect(710, 10, 450, 450))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_2.setFont(font)
        self.label_image_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_2.setObjectName("label_image_2")
        self.pushButton_open_file = QtWidgets.QPushButton(Form)
        self.pushButton_open_file.setGeometry(QtCore.QRect(60, 60, 111, 28))
        self.pushButton_open_file.setCheckable(False)
        self.pushButton_open_file.setDefault(True)
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.label_image_1 = QtWidgets.QLabel(Form)
        self.label_image_1.setGeometry(QtCore.QRect(250, 10, 450, 450))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_1.setFont(font)
        self.label_image_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_1.setScaledContents(False)
        self.label_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_1.setObjectName("label_image_1")
        self.label_image_3 = QtWidgets.QLabel(Form)
        self.label_image_3.setGeometry(QtCore.QRect(370, 470, 256, 256))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_3.setFont(font)
        self.label_image_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_3.setScaledContents(False)
        self.label_image_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_3.setObjectName("label_image_3")
        self.label_image_4 = QtWidgets.QLabel(Form)
        self.label_image_4.setGeometry(QtCore.QRect(820, 470, 256, 256))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_4.setFont(font)
        self.label_image_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_4.setObjectName("label_image_4")
        self.groupBox_1 = QtWidgets.QGroupBox(Form)
        self.groupBox_1.setGeometry(QtCore.QRect(30, 140, 181, 131))
        self.groupBox_1.setObjectName("groupBox_1")
        self.pushButton_brightness_change = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_brightness_change.setGeometry(QtCore.QRect(40, 80, 93, 28))
        self.pushButton_brightness_change.setObjectName("pushButton_brightness_change")
        self.spinBox_brightness_change = QtWidgets.QSpinBox(self.groupBox_1)
        self.spinBox_brightness_change.setGeometry(QtCore.QRect(100, 40, 46, 22))
        self.spinBox_brightness_change.setMinimum(-255)
        self.spinBox_brightness_change.setMaximum(255)
        self.spinBox_brightness_change.setProperty("value", 20)
        self.spinBox_brightness_change.setObjectName("spinBox_brightness_change")
        self.label = QtWidgets.QLabel(self.groupBox_1)
        self.label.setGeometry(QtCore.QRect(20, 40, 61, 21))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 310, 181, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_hist_equ = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_hist_equ.setGeometry(QtCore.QRect(40, 60, 93, 28))
        self.pushButton_hist_equ.setObjectName("pushButton_hist_equ")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "直方图均衡"))
        self.label_image_2.setText(_translate("Form", "处理后的图像"))
        self.pushButton_open_file.setText(_translate("Form", "打开图片"))
        self.label_image_1.setText(_translate("Form", "原图"))
        self.label_image_3.setText(_translate("Form", "原图直方图"))
        self.label_image_4.setText(_translate("Form", "处理后的图像直方图"))
        self.groupBox_1.setTitle(_translate("Form", "亮度均衡"))
        self.pushButton_brightness_change.setText(_translate("Form", "确定"))
        self.label.setText(_translate("Form", "均衡值"))
        self.groupBox_2.setTitle(_translate("Form", "直方图均衡"))
        self.pushButton_hist_equ.setText(_translate("Form", "确定"))

