# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_sub_window_6.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1269, 613)
        self.label_image_2 = QtWidgets.QLabel(Form)
        self.label_image_2.setGeometry(QtCore.QRect(720, 10, 450, 450))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_2.setFont(font)
        self.label_image_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_2.setObjectName("label_image_2")
        self.pushButton_open_file = QtWidgets.QPushButton(Form)
        self.pushButton_open_file.setGeometry(QtCore.QRect(60, 110, 111, 28))
        self.pushButton_open_file.setCheckable(False)
        self.pushButton_open_file.setDefault(True)
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.label_image_1 = QtWidgets.QLabel(Form)
        self.label_image_1.setGeometry(QtCore.QRect(250, 10, 450, 450))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_1.setFont(font)
        self.label_image_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_1.setScaledContents(False)
        self.label_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_1.setObjectName("label_image_1")
        self.groupBox_1 = QtWidgets.QGroupBox(Form)
        self.groupBox_1.setGeometry(QtCore.QRect(30, 180, 191, 271))
        self.groupBox_1.setObjectName("groupBox_1")
        self.pushButton_dct_process = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_dct_process.setGeometry(QtCore.QRect(50, 220, 93, 28))
        self.pushButton_dct_process.setObjectName("pushButton_dct_process")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 111, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_s1.setObjectName("radioButton_s1")
        self.verticalLayout.addWidget(self.radioButton_s1)
        self.radioButton_s3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_s3.setObjectName("radioButton_s3")
        self.verticalLayout.addWidget(self.radioButton_s3)
        self.radioButton_s6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_s6.setChecked(True)
        self.radioButton_s6.setObjectName("radioButton_s6")
        self.verticalLayout.addWidget(self.radioButton_s6)
        self.radioButton_s10 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_s10.setObjectName("radioButton_s10")
        self.verticalLayout.addWidget(self.radioButton_s10)
        self.radioButton_s15 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_s15.setObjectName("radioButton_s15")
        self.verticalLayout.addWidget(self.radioButton_s15)
        self.radioButton_s21 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_s21.setObjectName("radioButton_s21")
        self.verticalLayout.addWidget(self.radioButton_s21)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(920, 480, 93, 28))
        self.pushButton_save.setObjectName("pushButton_save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "基于DCT的图像压缩"))
        self.label_image_2.setText(_translate("Form", "处理后的图像"))
        self.pushButton_open_file.setText(_translate("Form", "打开图片"))
        self.label_image_1.setText(_translate("Form", "原图"))
        self.groupBox_1.setTitle(_translate("Form", "DCT保留的频域系数"))
        self.pushButton_dct_process.setText(_translate("Form", "确定"))
        self.radioButton_s1.setText(_translate("Form", "1个系数"))
        self.radioButton_s3.setText(_translate("Form", "3个系数"))
        self.radioButton_s6.setText(_translate("Form", "6个系数"))
        self.radioButton_s10.setText(_translate("Form", "10个系数"))
        self.radioButton_s15.setText(_translate("Form", "15个系数"))
        self.radioButton_s21.setText(_translate("Form", "21个系数"))
        self.label.setText(_translate("Form", "基于DCT的图像压缩"))
        self.pushButton_save.setText(_translate("Form", "保存该图像"))

