# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_sub_window_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1158, 789)
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(810, 10, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setGeometry(QtCore.QRect(240, 60, 900, 700))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image.setFont(font)
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.pushButton_open_file = QtWidgets.QPushButton(Form)
        self.pushButton_open_file.setGeometry(QtCore.QRect(20, 20, 191, 28))
        self.pushButton_open_file.setCheckable(False)
        self.pushButton_open_file.setDefault(True)
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 221, 81))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_gray_convert = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_gray_convert.setEnabled(False)
        self.pushButton_gray_convert.setGeometry(QtCore.QRect(50, 30, 121, 28))
        self.pushButton_gray_convert.setObjectName("pushButton_gray_convert")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 221, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_bin_convert_1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_bin_convert_1.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_bin_convert_1.setObjectName("label_bin_convert_1")
        self.pushButton_bin_convert = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_bin_convert.setEnabled(False)
        self.pushButton_bin_convert.setGeometry(QtCore.QRect(50, 60, 121, 28))
        self.pushButton_bin_convert.setObjectName("pushButton_bin_convert")
        self.spinBox_bin_threshold = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_bin_threshold.setGeometry(QtCore.QRect(135, 20, 61, 22))
        self.spinBox_bin_threshold.setMaximum(255)
        self.spinBox_bin_threshold.setProperty("value", 127)
        self.spinBox_bin_threshold.setObjectName("spinBox_bin_threshold")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 80, 149, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_color_space_1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_color_space_1.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_color_space_1.setFont(font)
        self.label_color_space_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_color_space_1.setObjectName("label_color_space_1")
        self.horizontalLayout.addWidget(self.label_color_space_1)
        self.label_color_space_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_color_space_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.label_color_space_2.setFont(font)
        self.label_color_space_2.setText("")
        self.label_color_space_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_color_space_2.setObjectName("label_color_space_2")
        self.horizontalLayout.addWidget(self.label_color_space_2)
        self.pushButton_reset = QtWidgets.QPushButton(Form)
        self.pushButton_reset.setEnabled(False)
        self.pushButton_reset.setGeometry(QtCore.QRect(60, 430, 121, 28))
        self.pushButton_reset.setObjectName("pushButton_reset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图像色彩空间转换"))
        self.label_title.setText(_translate("Form", "图像色彩空间转换"))
        self.label_image.setText(_translate("Form", "图片将显示在这里"))
        self.pushButton_open_file.setText(_translate("Form", "打开图片"))
        self.groupBox.setTitle(_translate("Form", "灰度转换"))
        self.pushButton_gray_convert.setText(_translate("Form", "灰度转换"))
        self.groupBox_2.setTitle(_translate("Form", "二值化"))
        self.label_bin_convert_1.setText(_translate("Form", "设置阈值："))
        self.pushButton_bin_convert.setText(_translate("Form", "二值化转换"))
        self.label_color_space_1.setText(_translate("Form", "当前色彩空间："))
        self.pushButton_reset.setText(_translate("Form", "恢复默认"))

